name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-dependencies
        path: ~/.cargo/registry/cache
        restore-keys: |
          ${{ runner.os }}-dependencies
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Retain artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: |
          target
          target/debug
